# Generated by Django 5.2.6 on 2025-09-30 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('file_url', models.URLField()),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumenty',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('cover_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FbAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fb_album_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('count', models.PositiveIntegerField(default=0)),
                ('cover_photo_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Album FB',
                'verbose_name_plural': 'Albumy FB',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('prezes', 'Prezes'), ('wiceprezes', 'Wiceprezes'), ('sekretarz', 'Sekretarz'), ('skarbnik', 'Skarbnik'), ('czlonek', 'Członek zarządu')], db_index=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('photo_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Władze',
                'ordering': ['order', 'role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Ręczny'), ('FACEBOOK', 'Facebook')], db_index=True, default='MANUAL', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('is_published', models.BooleanField(default=True)),
                ('fb_post_id', models.CharField(blank=True, max_length=64, unique=True)),
                ('fb_perma', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posty',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='FbPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fb_photo_id', models.CharField(max_length=64, unique=True)),
                ('created_time', models.DateTimeField(db_index=True)),
                ('permalink_url', models.URLField()),
                ('image_url', models.URLField()),
                ('thumb_url', models.URLField(blank=True)),
                ('caption', models.TextField(blank=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteapp.fbalbum')),
            ],
            options={
                'verbose_name': 'Zdjęcie FB',
                'verbose_name_plural': 'Zdjęcia FB',
                'ordering': ['-created_time'],
            },
        ),
    ]
