# Generated by Django 5.2.6 on 2025-10-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='fb_post_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
