# Generated by Django 5.2.6 on 2025-10-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_alter_post_options_alter_post_fb_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Slajd (hero)',
                'verbose_name_plural': 'Slajdy (hero)',
                'ordering': ['order', 'created'],
            },
        ),
    ]
