# Generated by Django 5.2.6 on 2025-10-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_heroimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='image_url',
            field=models.CharField(),
        ),
    ]
