# Generated by Django 5.2.7 on 2026-02-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_alter_heroimage_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['body', 'order', 'role', 'name'], 'verbose_name': 'Osoba', 'verbose_name_plural': 'Władze'},
        ),
        migrations.AddField(
            model_name='person',
            name='body',
            field=models.CharField(choices=[('zarzad', 'Zarząd Oddziału'), ('sad', 'Sąd Koleżeński Oddziału'), ('komisja', 'Komisja Rewizyjna Oddziału')], db_index=True, default='zarzad', max_length=20, verbose_name='Organ'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='person',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Kolejność wyświetlania w ramach organu'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('prezes', 'Prezes'), ('wiceprezes', 'Wiceprezes'), ('sekretarz', 'Sekretarz'), ('skarbnik', 'Skarbnik'), ('czlonek', 'Członek'), ('przewodniczacy', 'Przewodniczący'), ('zastepca', 'Zastępca przewodniczącego')], db_index=True, max_length=40, verbose_name='Funkcja'),
        ),
    ]
