# Generated by Django 5.2.7 on 2026-03-21 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_alter_person_options_person_body_alter_person_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='news/')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Podpis')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='siteapp.post', verbose_name='Aktualność')),
            ],
            options={
                'verbose_name': 'Zdjęcie aktualności',
                'verbose_name_plural': 'Zdjęcia aktualności',
                'ordering': ['order', 'id'],
            },
        ),
    ]
