# Generated by Django 5.2.7 on 2026-08-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0006_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='image_url',
            field=models.CharField(help_text='Ścieżka względna w static/, np. img/hero1.jpg', max_length=255),
        ),
    ]
