# Generated by Django 5.2.7 on 2026-08-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0007_alter_heroimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbphoto',
            name='album',
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Podpis')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='siteapp.event', verbose_name='Wydarzenie')),
            ],
            options={
                'verbose_name': 'Zdjęcie z wydarzenia',
                'verbose_name_plural': 'Zdjęcia z wydarzeń',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='FbAlbum',
        ),
        migrations.DeleteModel(
            name='FbPhoto',
        ),
    ]
