# Generated by Django 5.2.7 on 2026-08-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0008_remove_fbphoto_album_eventphoto_delete_fbalbum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wp_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField(blank=True)),
                ('link', models.URLField()),
                ('image_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Aktualność z centrali PTTK',
                'verbose_name_plural': 'Aktualności z centrali PTTK',
                'ordering': ['-published_at'],
            },
        ),
    ]
