# Generated by Django 5.2.7 on 2026-08-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0009_centralnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/', verbose_name='Plik'),
        ),
        migrations.AddField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='hero/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, help_text='Użyj tylko, gdy dokument jest hostowany gdzie indziej. W innym wypadku wgraj plik powyżej.', verbose_name='Link zewnętrzny (zaawansowane)'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='image_url',
            field=models.CharField(blank=True, help_text='Tylko dla starszych wpisów. Nowe zdjęcia wgrywaj przez pole „Zdjęcie” powyżej.', max_length=255, verbose_name='Ścieżka statyczna (zaawansowane)'),
        ),
    ]
