# Generated by Django 5.2.7 on 2026-08-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0012_create_redaktor_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at'], 'verbose_name': 'Aktualność', 'verbose_name_plural': 'Aktualności'},
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, max_length=120, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Widoczny publicznie'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_url',
            field=models.URLField(blank=True, verbose_name='Zdjęcie okładkowe (stary URL, zaawansowane)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Opublikowane'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Miejsce'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='Slug (adres w URL)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Kolejność'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='title',
            field=models.CharField(blank=True, max_length=140, verbose_name='Tytuł (opcjonalnie)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Kolejność wyświetlania w ramach organu', verbose_name='Kolejność'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo_url',
            field=models.URLField(blank=True, verbose_name='Zdjęcie (URL, nieużywane obecnie na stronie)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fb_perma',
            field=models.URLField(blank=True, verbose_name='Link do posta na Facebooku'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Zdjęcie (stary URL, zaawansowane)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Opublikowana'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(db_index=True, verbose_name='Data publikacji'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Zdjęcie'),
        ),
    ]
