# Generated by Django 5.2.7 on 2026-08-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0014_document_deleted_at_document_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Miejsce — szerokość geogr.'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Miejsce — długość geogr.'),
        ),
    ]
