# Generated by Django 5.2.7 on 2026-08-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0015_event_location_lat_event_location_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Miejsce zakończenia'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Godzina zakończenia'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Godzina rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Miejsce rozpoczęcia'),
        ),
    ]
