# Generated by Django 5.2.7 on 2026-08-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0016_event_end_location_event_end_time_event_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Miejsce zakończenia — szerokość geogr.'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_location_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Miejsce zakończenia — długość geogr.'),
        ),
    ]
