# Generated by Django 5.2.7 on 2026-08-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0017_event_end_location_lat_event_end_location_lng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centralnews',
            options={'ordering': ['-published_at'], 'verbose_name': 'Aktualność zewnętrzna PTTK', 'verbose_name_plural': 'Aktualności zewnętrzne PTTK'},
        ),
        migrations.AddField(
            model_name='centralnews',
            name='source',
            field=models.CharField(choices=[('centrala', 'Centrala PTTK'), ('wko', 'Wielkopolska Korporacja Oddziałów PTTK')], default='centrala', max_length=20),
        ),
        migrations.AlterField(
            model_name='centralnews',
            name='wp_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='centralnews',
            constraint=models.UniqueConstraint(fields=('source', 'wp_id'), name='uniq_centralnews_source_wp_id'),
        ),
    ]
